# Generated by Django 3.1 on 2020-08-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('p', 'primary'), ('s', 'secondary'), ('d', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
