# Generated by Django 3.1 on 2020-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreplatform', '0004_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
