# Generated by Django 3.1 on 2020-08-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreplatform', '0007_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
